name: Build & Publish homio-dependency

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.MAVEN_USERNAME }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --reload gpg-agent
        env:
          GPG_TTY: /dev/tty

      - name: Build & Publish
        run: mvn clean deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Trigger Project Builds for All Repositories
        run: |
          REPOS=(
            "homiodev/homio-api"
          )
          for REPO in "${REPOS[@]}"; do
            echo "Triggering build for $REPO"
            curl -X POST https://api.github.com/repos/$REPO/dispatches \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -d '{"event_type": "trigger-build"}'
          done
